### ISSUE TITLE
Switch is not available

### ISSUE THREAD

**Issue by maodun96** [niceboygithub/AqaraSmartSwitchS1E#28]
I have five S1E devices. Two of them have been successfully connected to MQTT and are functioning normally. However, two of the relay switches are showing an "unavailable" status, as shown in the picture. Additionally, one of the devices failed to be added properly.

Previously, all five switches had been connected to MQTT, and at that time, all the relay switches were displaying an "unavailable" status. Interestingly, two of the switches later unexpectedly returned to a normal state under unknown circumstances.

![image](https://github.com/niceboygithub/AqaraSmartSwitchS1E/assets/43996175/d0edc61a-3229-4619-9b59-14f461077717)

**Comment by niceboygithub** [comment]
What are the versions of S1E and S1E2HA?

**Comment by maodun96** [comment]
> What are the versions of S1E and S1E2HA?
Both S1E and S1E2HA are updated to the latest according to the project. These are all recent operations.

If you're referring to versions with multiple iterations of hardware, I'm not sure. I bought it in August 2023.

**Comment by maodun96** [comment]
> What are the versions of S1E and S1E2HA?

Both S1E and S1E2HA are updated to the latest according to the project. These are all recent operations.
If you're referring to versions with multiple iterations of hardware, I'm not sure. I bought it in August 2023.

**Comment by maodun96** [comment]
hello ,@niceboygithub 

Through the 'top' command in telnet, I have found that the two processes:
ha_driven -O1 -L7
ha_driven -O 1 -L 7 -p /tmp/automatic.pid

are consistently consuming a total of 20% of the memory when using the problematic switches. The switches that are working normally do not exhibit similar memory usage.

**Comment by maodun96** [comment]
I recall that I used the ”gw_global_tool.ttl“  to remove the password and flash the firmware. I did not go through the interrupt uboot process. Will this have any impact?

**Comment by maodun96** [comment]
hi, @niceboygithub 

This is the state after running the top command. The cached memory is abnormal.

`Mem: 41512K used, 15348K free, 0K shrd, 857416K buff, 857464K cached
CPU:  0.0% usr  4.5% sys  0.0% nic 95.4% idle  0.0% io  0.0% irq  0.0% sirq
Load average: 6.04 6.06 6.00 1/110 3042
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
  814     1 root     S    13740 24.1   1  4.5 /bin/aqgui -F /res -l d
  802     1 root     S    11396 20.0   0  0.0 ha_master  -H -S -a /lib/libha_auto.so
  799     1 root     S     5680  9.9   0  0.0 ha_lanbox
 3202     1 root     S     5452  9.5   1  0.0 wpa_supplicant -D nl80211 -i wlan0 -c /tmp/wpa_supplicant.conf -B -W
  956   846 root     S     4800  8.4   1  0.0 ha_driven -O 1 -L 7 -p /tmp/automatic.pid
  798     1 root     S     4184  7.3   0  0.0 ha_basis
  796     1 root     S     3852  6.7   1  0.0 ha_agent -D
  756     1 root     S     3088  5.4   1  0.0 /bin/sysservice -l d
  958   846 root     S     2576  4.5   1  0.0 {res_monitor.sh} /bin/sh /data/bin/res_monitor.sh
  846     1 root     S     2576  4.5   1  0.0 {res_monitor.sh} /bin/sh /data/bin/res_monitor.sh
  758     1 root     S     2568  4.5   1  0.0 telnetd
    1     0 root     S     2452  4.3   1  0.0 {linuxrc} init
 2961     1 root     S     2452  4.3   1  0.0 -/bin/login
 3148   846 root     S     2448  4.3   0  0.0 {app_monitor.sh} /bin/sh /tmp/app_monitor.sh
  815     1 root     S     2448  4.3   0  0.0 {gui_monitor.sh} /bin/sh /bin/gui_monitor.sh
  805     1 root     S     2448  4.3   1  0.0 {Aries.sh} /bin/sh /bin/Aries.sh
 1199   845 root     S     2448  4.3   1  0.0 {ubus_monitor.sh} /bin/sh /data/bin/ubus_monitor.sh
 1146   844 root     S     2448  4.3   0  0.0 {mqtt_sub.sh} /bin/sh /data/bin/mqtt_sub.sh
  957   846 root     S     2448  4.3   1  0.0 awk /method|sendHeartbeat {print $7 $8}
 1197   845 root     S     2448  4.3   1  0.0 awk {$1=$2=$3=$4=" ; print $0}
  844     1 root     S     2448  4.3   0  0.0 {mqtt_sub.sh} /bin/sh /data/bin/mqtt_sub.sh
  845     1 root     S     2448  4.3   1  0.0 {ubus_monitor.sh} /bin/sh /data/bin/ubus_monitor.sh
 3042  3024 root     R     2448  4.3   1  0.0 top
 3024   758 root     S     2448  4.3   1  0.0 -sh
 3243     1 root     S     2448  4.3   1  0.0 udhcpc -i wlan0 -s /etc/udhcp/simple.script -x hostname Magic-Switch-S1E-4E00 -t 10
 3026   815 root     S     2316  4.0   0  0.0 sleep 5
 3028  3148 root     S     2316  4.0   0  0.0 sleep 5
 3041   805 root     S     2316  4.0   1  0.0 sleep 10
  792     1 root     S     2296  4.0   1  0.0 mdnsd
  739     1 root     S     2236  3.9   0  0.0 /bin/fwfs --block_size=131072 --subblock_size=32768 --block_cycles=500 --read_size=2048 --prog_size=2048 --cache_size=32768 --file_cache_size=32768 --cache_pool_size=2 --block_count=8 --lookahead_size=8 /dev/mtd10 /misc
  744     1 root     S     1784  3.1   1  0.0 ubusd
 1196   845 root     S     1752  3.0   1  0.0 ubus -v monitor
 1145   844 root     S     1592  2.8   0  0.0 /bin/mosquitto_sub -h 192.168.10.132 -u mqtt -P 123456 -p 1883 -v -t homeassistant/+/0x0054ef44534e00/# -t homeassistant/status
  749     1 root     S     1456  2.5   1  0.0 property_service -i /etc/build.prop -p /data/storage/prop.dat -b
  740     1 root     S     1376  2.4   0  0.0 watchdog_30S
  564     2 root     SW       0  0.0   1  0.0 [kworker/1:1]
  617     2 root     SW       0  0.0   1  0.0 [ksdioirqd/mmc0]
  255     2 root     SW       0  0.0   0  0.0 [kworker/0:1]
 1111     2 root     DW       0  0.0   0  0.0 [disp0_P0_MAIN]
 1114     2 root     DW       0  0.0   0  0.0 [MI_FB_SYNC_DISP]
  670     2 root     SW       0  0.0   0  0.0 [bl_wdog/mmc0:00]
  657     2 root     DWN      0  0.0   1  0.0 [mi_log]
 3014     2 root     SW       0  0.0   0  0.0 [kworker/0:0]
    7     2 root     SW       0  0.0   0  0.0 [rcu_preempt]
 1934     2 root     SW<      0  0.0   0  0.0 [kworker/u5:1]
   22     2 root     SW       0  0.0   1  0.0 [kworker/u4:1]
 3227     2 root     SW<      0  0.0   1  0.0 [kworker/u5:0]
    3     2 root     SW       0  0.0   0  0.0 [ksoftirqd/0]
   16     2 root     SW       0  0.0   1  0.0 [migration/1]
 2556     2 root     SW<      0  0.0   1  0.0 [kworker/u5:2]
   17     2 root     SW       0  0.0   1  0.0 [ksoftirqd/1]
   10     2 root     SW       0  0.0   0  0.0 [migration/0]
  491     2 root     SW       0  0.0   1  0.0 [monitor_temp]
  354     2 root     SW       0  0.0   0  0.0 [kswapd0]
  214     2 root     SW       0  0.0   1  0.0 [kcompactd0]
  731     2 root     SW       0  0.0   1  0.0 [ubi_bgt1d]
 1959     2 root     SW       0  0.0   1  0.0 [kworker/u4:2]
   12     2 root     SW       0  0.0   0  0.0 [watchdog/0]
   20     2 root     SW       0  0.0   1  0.0 [kdevtmpfs]
  622     2 root     DW       0  0.0   1  0.0 [IspDriverThread]
  626     2 root     DW       0  0.0   0  0.0 [IspMidThreadWq]
  654     2 root     SW       0  0.0   0  0.0 [mi_wq]
    2     0 root     SW       0  0.0   0  0.0 [kthreadd]
    5     2 root     SW<      0  0.0   0  0.0 [kworker/0:0H]
`

**Comment by s94949494** [comment]
My s1e switch doesn't work too
S1E 2.20
S1E2HA 1.0.8
![Screenshot_2024-07-27-01-35-27-503_io homeassistant companion android](https://github.com/user-attachments/assets/639ad749-d99c-4170-8bb1-b1ef9152ed58)
![Screenshot_2024-07-27-01-35-30-628_io homeassistant companion android](https://github.com/user-attachments/assets/1a6be6ad-4724-46a5-a2f4-22e553191f69)
![Screenshot_2024-07-27-01-35-33-643_io homeassistant companion android](https://github.com/user-attachments/assets/36c915b3-91b5-4651-b0b3-b3faa2caac79)

**Comment by lglw** [comment]
I have exactly the same problem

**Comment by oopuuu** [comment]
Try [this](https://github.com/niceboygithub/AqaraSmartSwitchS1E/issues/34#issuecomment-2558172070)

**Comment by oopuuu** [comment]
> I have exactly the same problem

Try [this](https://github.com/niceboygithub/AqaraSmartSwitchS1E/issues/34#issuecomment-2558172070)

**Comment by maodun96** [comment]
> Try [this](https://github.com/niceboygithub/AqaraSmartSwitchS1E/issues/34#issuecomment-2558172070)

感谢老哥，我已经用不到了，给其他同学一个参考。（已经开始往外卖了

**Comment by s94949494** [comment]
> 試試[這個](https://github.com/niceboygithub/AqaraSmartSwitchS1E/issues/34#issuecomment-2558172070)

謝謝，照你的方式已可成功控制開關
其他選項主題或者字體這還是不可用，有方法修改嗎
![123](https://github.com/user-attachments/assets/c3990844-d978-4f90-9918-ce5eefc91069)

**Comment by startrace111** [comment]
> > 試試[這個](https://github.com/niceboygithub/AqaraSmartSwitchS1E/issues/34#issuecomment-2558172070)
> 
> 謝謝，照你的方式已可成功控制開關 其他選項主題或者字體這還是不可用，有方法修改嗎 ![123](https://github.com/user-attachments/assets/c3990844-d978-4f90-9918-ce5eefc91069)

try my repo, I have fixed this problem: [this](https://github.com/startrace111/AqaraSmartSwitchS1E)

**Comment by s94949494** [comment]
> > > 試試[這個](https://github.com/niceboygithub/AqaraSmartSwitchS1E/issues/34#issuecomment-2558172070)
> > 
> > 
> > 謝謝，照你的方式已可成功控制切換其他選項主題或字體這還是不可用，有方法修改嗎![123](https://github.com/user-attachments/assets/c3990844-d978-4f90-9918-ce5eefc91069)
> 
> 嘗試我的 repo，我已經修復了這個問題：[這個](https://github.com/startrace111/AqaraSmartSwitchS1E)

I try , but still have problem

![Image](https://github.com/user-attachments/assets/cce19b40-bc71-40d0-910c-0483124cffea)

![Image](https://github.com/user-attachments/assets/d476a494-315f-40d9-955d-f0c79994087c)

![Image](https://github.com/user-attachments/assets/64e27f4f-288f-41a9-949c-c961008c5f55)

**Comment by startrace111** [comment]
> > > > 試試[這個](https://github.com/niceboygithub/AqaraSmartSwitchS1E/issues/34#issuecomment-2558172070)
> > > 
> > > 
> > > 謝謝，照你的方式已可成功控制切換其他選項主題或字體這還是不可用，有方法修改嗎![123](https://github.com/user-attachments/assets/c3990844-d978-4f90-9918-ce5eefc91069)
> > 
> > 嘗試我的 repo，我已經修復了這個問題：[這個](https://github.com/startrace111/AqaraSmartSwitchS1E)
> 
> I try , but still have problem
> 
> ![Image](https://github.com/user-attachments/assets/cce19b40-bc71-40d0-910c-0483124cffea)
> 
> ![Image](https://github.com/user-attachments/assets/d476a494-315f-40d9-955d-f0c79994087c)
> 
> ![Image](https://github.com/user-attachments/assets/64e27f4f-288f-41a9-949c-c961008c5f55)

Not s1e_update.sh, use install_s1e2ha.sh this script

**Comment by s94949494** [comment]
> > > > > 試試[這個](https://github.com/niceboygithub/AqaraSmartSwitchS1E/issues/34#issuecomment-2558172070)
> > > > 
> > > > 
> > > > 謝謝，照你的方式已可成功控制切換其他選項主題或字體這還是不可用，有方法修改嗎![123](https://github.com/user-attachments/assets/c3990844-d978-4f90-9918-ce5eefc91069)
> > > 
> > > 
> > > 嘗試我的 repo，我已經修復了這個問題：[這個](https://github.com/startrace111/AqaraSmartSwitchS1E)
> > 
> > 
> > I try , but still have problem
> > ![Image](https://github.com/user-attachments/assets/cce19b40-bc71-40d0-910c-0483124cffea)
> > ![Image](https://github.com/user-attachments/assets/d476a494-315f-40d9-955d-f0c79994087c)
> > ![Image](https://github.com/user-attachments/assets/64e27f4f-288f-41a9-949c-c961008c5f55)
> 
> Not s1e_update.sh, use install_s1e2ha.sh this script

thx bro , it can work.

**Comment by zoffypal** [comment]
> > > 試試[這個](https://github.com/niceboygithub/AqaraSmartSwitchS1E/issues/34#issuecomment-2558172070)
> > 
> > 
> > 謝謝，照你的方式已可成功控制開關 其他選項主題或者字體這還是不可用，有方法修改嗎 ![123](https://github.com/user-attachments/assets/c3990844-d978-4f90-9918-ce5eefc91069)
> 
> try my repo, I have fixed this problem: [this](https://github.com/startrace111/AqaraSmartSwitchS1E)

Thank you, all entities available with your repo.
However, sometimes the switch can't read with correct status especially quick on and off in few seconds, or can't send MQTT command to S1E, switch back to previous status and no MQTT logs about that. In my case, need to wait about 10s then send MQTT command to S1E and it will get work.
